#!/usr/bin/env php
<?php

include(__DIR__.DIRECTORY_SEPARATOR.'functions'.DIRECTORY_SEPARATOR.'load.php');

// Gather options

if (in_array('--no-subdirectories', $argv)) {
	$createSubDirectories = false;
} else {
	$createSubDirectories = true;
}

if (in_array('--create-directory', $argv)) {
	$createDirectory = true;
} else {
	$createDirectory = false;
}

if (in_array('--keep-directory', $argv)) {
	$keepDirectory = true;
} else {
	$keepDirectory = false;
}

// Check parameters
if (!isset($argv[1])) {
	
	doLog('No source file specified'."\n");
	exit();	   
	
} else if (!is_file($argv[1])) {
	
	doLog('Source file not found'."\n");
	exit();	 
}
	
if (!isset($argv[2])) {

	doLog('No destination directory specified'."\n");
	exit(); 
	   
} else if (!is_dir(dirname($argv[2]))) {
	
	if ($createDirectory) {
		if (!mkdir($argv[2], 0755, true)) {
			doLog('Could not create directory '.$argv[2]."\n");
			exit();
		}
	} else {
		doLog('Parent directory '.dirname($argv[2]).' not found'."\n");
		exit();	 
	}
	
}
		
// Process file
$processor = new FMXMLProcessor($argv[1], $argv[2], $createSubDirectories, $keepDirectory);
$processor->process();

exit();